### ISSUE TITLE
application alway dump

### ISSUE THREAD

**Issue by bubbleatgit** [EmuDevs/EDWoWGMClient#2]
![qq 20150907170659](https://cloud.githubusercontent.com/assets/7858776/9713261/e32096ce-5582-11e5-9acc-3b22c179ff4b.jpg)

i hope there have a doc for this application

**Comment by bubbleatgit** [comment]
![qq 20150907172730](https://cloud.githubusercontent.com/assets/7858776/9713756/0a12a062-5586-11e5-9f19-f7138f9359cc.png)

**Comment by Faded** [comment]
This application isn't quite finished. The only documentation is what's written in the comments, you can try visiting emudevs.com and posting a help thread.
